### PR TITLE
Gen 8 mechanics updates + fixes

### PR DESCRIPTION
**Pull request by ErwanBeurier**
Summary: (2020-11-18)
 - I am following this [Smogon post](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/). 
 - I implement + test everything that is not already implemented in Essentials.
 - Done with the "Changes to Old Mechanics" section
 - Done with the "Misc" section (with a few exceptions that I don't understand; see detailed TODO list)
 - Done with the "Items" section
 - Done with the "Abilities" section
 - The "New abilities" section from IoA DLC (done in #66 )
 - The "New moves" section from IoA DLC (done in #66 )
 - Updated tm.txt for returning old Pokémons
 - Done with the "Moves" section (with a few exceptions: see detailed TODO list)

---------
First commits:
 - Fixed typo Hattena instead of Hatenna in tm.txt
 - Lunar Dance/Healing Wish now activate only if the receiver isn't at full HP or has a status; if the new battler is healthy, the effect is stored (tested)
 - Neutralising Gas is made ungainable
 - Added detailed TODO list (all the gen 8 mechanics updates)

Question: is it better to make one PR per few updates, or one PR containing all the updates?

### CODE REVIEW

**Comment by ErwanBeurier** [comment]
Done:
 - Healing Wish / Lunar Dance interaction with Ally Switch (tested)
 - Defiant/Competitive activate on stat loss reflected by Mirror Armor (tested)
 - If a TR is flinged, the base damage of Fling will be the base damage of the move of the TR (tested)

**Comment by ErwanBeurier** [comment]
Done: 
 - Throat Spray does not activate when the move does not hit (tested)
 - Blunder Policy still activates when a move with multiple targets misses one target (tested)

Next:
 - New stuff regarding Eject Pack + Utility Umbrella.

**Comment by ErwanBeurier** [comment]
Done:
 - Utility Umbrella adjustments

Man this item is awful, not in itself, but because nobody really seems to understand what it does. I ended up following [Smogon's description](https://www.smogon.com/dex/ss/items/utility-umbrella/): the Utility Umbrella ignores only Sun/Harsh Sun/Rain/Heavy Rain, and changes nothing related to Sandstorm and Hail. 
Concerning move damage + accuracy, the holder ignores weather if it is the target, not if it is the user. Concerning abilities (e.g. Chlorophyl) or self-targetting moves (e.g. Synthesis), the holder ignores weather. (My guess is that the Umbrella only ignores whenever the holder is the target, in any sense: target of the move, target of the ability).

**Comment by ErwanBeurier** [comment]
Done:
 - Eject Pack and Eject Button stuff (tested)
Only one Pokémon can switch per move (so Eject Pack will not activate if holder is targeted by Parting Shot + only one Eject Pack/Button can activate per move). 

Edited the TODO list: everything listed under the "Items" section is done. 
Next step: abilities.

**Comment by ErwanBeurier** [comment]
Done:
 - Mirror Armor doesn't activate if the Pokémon with Mirror Armor already has -6 in the stat in question (tested)
 - The reflected stat drop is blocked by the opponent's substitute (tested)
 - Strength Sap still works but the stat drop is reflected (tested)

**Comment by ErwanBeurier** [comment]
Done: 
 - Cramorant doesn't change form if Surf doesn't hit (tested)
 - Cramorant doesn't do damage to Pokémons with Magic Guard (tested)

I also tested how Cramorant works in Essentials: and as far as I can tell, it's working perfectly now.

**Comment by ErwanBeurier** [comment]
Done:
 - Pastel Veil now cures Poison (if poisoned by Mold Breaker) (tested)
 - Made Hunger Switch ungainable (cannot switch abilities with someone with Hunger Switch) (tested)
 - Tested Ice Face, checked that it worked like described in the Smogon post.

**Comment by ErwanBeurier** [comment]
Done:
 - Changing Steely Spirit, Ice Scales and Punk Rock's action on the "mults" variable (boost base damage/final damage instead of attack/defense).

**Comment by ErwanBeurier** [comment]
Done:
 - Neutralising Gas immediately activates when the holder switches out (which means that [Intimidate reactivates on the mon with Neutralizing Gas, just before it switches out](https://bulbapedia.bulbagarden.net/wiki/Neutralizing_Gas_(Ability))) (tested)
 - The speed boost of Unburden is back when Neutralising Gas stops (tested, but I had nothing to implement)
 - Neutralizing Gas activates before any other ability (tested)

Neutralising Gas VS the world. At least I'm done with this ability.

**Comment by ErwanBeurier** [comment]
Done: 
 - If Ditto has Mimicry (by transforming into Galarian Stunfisk), if the terrain stops, its type reverts to Normal (instead of Ground/Steel, which is Stunfisk's original type) (tested)

Phew. I'm done with abilities. Next step is moves.

**Comment by ErwanBeurier** [comment]
Done:
 - Added PokeBattle_Move_199 for Behemoth Blade, even if Dynamax is not implemented
 - Made Pyro Ball a bullet move, made Fishious Rend a biting move, made Magic Power a powder move (no scripting here, only PBS)
 - Fixed Clagorous Soul failing when one of the stats was at +6 (should fail only if all the stats are +6)
 - Tiny fix for Grav Apple

**Comment by Golisopod-User** [comment]
Hey there. I've covered this so you can remove it from the To-Do list.

 - Turn order now changes dynamically mid-turn whenever Speed changes (Pan.), but alterations like Quick Claw or Lagging Tail will not change turn order again once the turn has started (Anubis). Obtaining Prankster mid-turn does change turn order (Anubis), but obtaining Stall does not (Anubis).
 
I've also covered all of the IoA mechanics and am going through the Smogon thread to see if anything major for Crown Tundra has been covered. So you can remove the IoA stuff from the To Do list too.

Also, I'm in the process of updating the Level-Up learnsets of the Pokemon returning in Crown Tundra and I have only about 30 Pokemon left to complete. But I can't complete the TM data for them so could you cover that?

**Comment by ErwanBeurier** [comment]
Hi @Golisopod-User !

> Hey there. I've covered this so you can remove it from the To-Do list.
> 
>     * Turn order now changes dynamically mid-turn whenever Speed changes (Pan.), but alterations like Quick Claw or Lagging Tail will not change turn order again once the turn has started (Anubis). Obtaining Prankster mid-turn does change turn order (Anubis), but obtaining Stall does not (Anubis).
Nice! When I read the code and found many recalculations of "priority" I wasn't sure if they were up-to-date or not. 

> I've also covered all of the IoA mechanics and am going through the Smogon thread to see if anything major for Crown Tundra has been covered. So you can remove the IoA stuff from the To Do list too.
I updated the TODO list.

> Also, I'm in the process of updating the Level-Up learnsets of the Pokemon returning in Crown Tundra and I have only about 30 Pokemon left to complete. But I can't complete the TM data for them so could you cover that?
I will handle the tm file.

**Comment by ErwanBeurier** [comment]
Done:
 - Updating tm.txt for returning old Pokémons (complete).

**Comment by ErwanBeurier** [comment]
Done:
 - Teatime stuff: bypasses Substitute (tested) + tested whether the rest was already implemented or not
 - No Retreat: everything works (tested)
 - Octolock activates Defiant/Competitive, but not Mirror Armor (tested)

**Comment by ErwanBeurier** [comment]
Done:
 - Sticky Web now stores its user, so that Court Change'd Sticky Web doesn't trigger Defiant/Competitive (tested)
 - In doubles, Dragon Darts hits the target + its ally; if one of them is invulnerable, is Fairy type, or is protecting, then the other one takes both hits. (tested)
 - Updated PBS so Dragon Darts hits one NearOther, not AllNearFoes (tested)
 - Wide Guard does not protect from Dragon Darts, even if it hits twice (tested)
 - Found and fixed a bug where the second Dragon Dart would consider an un-updated damageState from the second target (tested)

Dragon Darts is horrible. I get the feeling that half of its properties are bugs, not features. Speaking of that, there are two properties that I won't implement just now (maybe later, but I'd rather leave them for now). I have implemented/tested everything that is on the Bulbapedia page.

**Comment by ErwanBeurier** [comment]
Done:
 - Tested Life Dew, triggers ally's immunity to Water.

What's left to implement:
 - Dragon Dart subtle-ish/buggy stuff
 - Teatime's activation order.
(See TODO list for details on these)
IMO, we should ignore these, they are details that probably nobody would ever notice/search in a fangame.

**Pull request merged**
