### PR TITLE
Changed multiplying by self to exponent

### PR DESCRIPTION
**Pull request by Keyacom**
`deviation * deviation` is longer than `deviation ** 2`. That's why I changed it.

### CODE REVIEW

**Comment by Maruno17** [comment]
This is really petty.

**Comment by Keyacom** [comment]
I will try to check for other cases of a number multiplying by itself and replace them with exponents.

**Comment by Keyacom** [comment]
NOTE: The commit above modified 10 files, but the name says 3 because I forgot to change it.

**Comment by Maruno17** [comment]
Having more examples doesn't make it less petty. What's the point?

**Comment by Keyacom** [comment]
This might be a minor application of DRY (Don't Repeat Yourself), which doesn't apply just to iteration, but to general repetition. That's why I put exponentiation here.

**Comment by Keyacom** [comment]
Due to possible merge conflicts, this PR will be closed now.

**Pull request closed without merging**
