### PR TITLE
Modular Pause Menu, Pokegear Menu and Event Handlers

### PR DESCRIPTION
**Pull request by Golisopod-User**
Made multiple system modular to allow plugins to easily add/remove/edit functions without the need to overwrite large sections of code.

- Made the Pause Menu modular by registering the pause menu options using handler hashes.
- Made the Pokegear Menu modular by registering the Pokegear options using handler hashes. 
- Made the Pokegear menu screen-size agnostic.
- Converted all EventHandlers to hashes of procs to allow easy addition and removal of the Event procs by plugins.
- Added ability flag "FasterEggHatch" to check for abilities which decrease hatching steps faster.
- Added  item flag "Repel" to check for for Repel-like items.

### CODE REVIEW

**Comment by Maruno17** [comment]
There's repeated code in `module PauseMenuCommands` and `module PokegearCommands`, and inevitably for the Options screen options when that gets overhauled in the same way. I think this code can be generalised into a mixin module similar to how the `GameData` classes work, or in whatever way works for modules. This is a refactoring concern, though, and may be beyond the scope of this pull request; I just think there may be a few too many event handler-type classes and associated helper modules floating around now.

Further, each command added to these modules should have a priority/position. Shown commands are shown in order depending on that priority. I would suggest that the standard commands be spaced 20 apart (i.e. 20, 40, 60...) to leave plenty of room for devs to insert their own commands wherever they want into the list. The first command should **not** be 0, but start at 20, because devs may well want to add a command to the top of the list.

`module PokemonPCList` may want to be rewritten to be more consistent with these modules (or these modules rewritten to be more consistent with `PokemonPCList`, whatever). I don't know if you'd consider that to be beyond the scope of this pull request.

Perhaps the "name" value should support both strings (as they currently are) and procs, to allow dynamic command names. The pause menu command which is the player's name can use this instead of `_INTL("\\PN")`, which is a bit of a weird thing to write.

I think it would help if you keep future pull requests more focussed. For example, one for rewriting event registering, one for turning the pause menu's/Pokégear menu's commands into hashes of registered entries, one for improving the Pokégear's screen, and one for the addition of more flags to PBS files and their effects. You're already able to make multiple pull requests at once, so the less kitchen sink-y they are, the better.

**Comment by Golisopod-User** [comment]
I've made the dynamic option name and option priority changes you described, but I've made the difference between the "priorities" 10 instead of 20, because that seemed more reasonable.

I've also addressed the abundance of menu handler modules by creating one `MenuHandlers` module which is a mixin for all the new handler modules added by this PR, as well as the existing Debug Menu handlers.

I've also rewritten `module PokemonPCList` to be similar to the other menu handlers, because it was super easy. I would've tackled the option screen too, but decided not to, manly because it can technically be edited by Plugins (because of the function `pbAddOnOptions`) and because, as you mentioned, this PR already handles alot, so I'd much rather deal with that in another PR.

I apologize for throwing a bunch of stuff into this PR all willy-nilly. The sudden announcement of v20 being ready for release and the ambiguity of said release's date threw me for a loop. I'll try to avoid this in the future.

**Comment by Maruno17** [comment]
You've done the priority numbers backwards compared to how I would have done them. The smallest number should come first in the list.

I'm also wondering about whether the "name" values (the ones that are strings, not procs) would actually translate themselves. I know they have `_INTL` around themselves, but I'd guess that it would be evaluated as soon as it was registered (i.e. before the player has chosen a language, so it ends up staying the same), and then just becomes a string which is used forever without trying to translate it again via `_INTL`. Maybe all text visible to the player should be in a proc, so that it can be evaluated (and translated) when queried. It's a bit clunky, but I don't see any alternative.

You've also moved the Hall of Fame/Purify Chamber registrations out of their respective scripts, which I don't think is a good idea. I get that you've done so because `MenuHandlers::PokemonPC` needs to be defined before anything should be allowed to register to it, but this reduces modularity. The classes and modules for the UI menus should probably go in the folder "Game processing" in a new script section, so they're near the beginning of all scripts and are loaded way before anything tries to register with them.

Thinking about it, maybe we shouldn't have separate classes for each UI menu's contents. `module MenuHandlers` could contain a single hash (empty by default) and the helper methods directly. The helper methods would be called like `MenuHandlers.register("pc", "trainer_pc", { name/condition/priority/effect })`. If the hash doesn't already contain anything for the key "pc", it would add a `HandlerHashBasic.new` into that hash with that key, and then register "trainer_pc" and its value into the HandlerHashBasic for "pc". This also makes it trivial to add more menus to it.

The above could also be done for `module Events`, instead of the mass of methods and `@@something` variables it currently has: `Events.register(:on_step_taken, :poison_party, proc { whatever })`.

For both of the above, we should at least be consistent with using strings or symbols to identify a "category" ("pc" or "pause_menu" or "on_step_taken") and an identifier ("hall_of_fame" or "fill_bag" or "poison_pokemon"). I imagine symbols are more recommended for this.

**Comment by Golisopod-User** [comment]
When I think of "priority", I think of high to low. So high priority items appear at the top of the menu and low priority items appear at the bottom. If we're starting from 0, then it should be called "index" and not "priority".

I think the hash of handlers for `module MenuHandlers` and `module Events` could work well. I'll implement that. I'll be using symbol notation to be consistent with GameData. I don't know if its worth keeping compatibility for the old `module Events` though, so should I remove that stuff completely? Would it also be worth merging `module EncounterModifiers` into this new Event system?

Also, if the names for the menu options are an issue, then wouldn't that also apply to all the hardcoded GameData classes too? They pretty much work the same way, in terms of being registered and evaluated before the player has the chance to select a language. I could implement the solution you have for those in the MenuHandlers too.

**Comment by Maruno17** [comment]
I don't think "index" is quite the right word for it, because the first option won't be at index number 10. Maybe "order"?

I think we can immediately remove the methods in `module Events` (rather than deprecating them for a version), because of the removal of `sender` as per below. There isn't a `module EncounterModifiers` - there's a script section called that, and it just contains some `Events.onWildPokemonCreate` registrations.

For the hardcoded GameData classes, the names of each thing being registered are only in `_INTL()` to ensure that they are picked up when extracting all text from the game. The thing that does the translation while playing the game is `def name` in each class. It's a little awkward, but I believe it works (and some PBS files use the untranslated names, so both original and translated versions of the texts are needed). Maybe `def each_available` can yield a third value which is the translated name of the option, so it's immediately available when iterating through the options. It looks like `*args` is never used for `def get_string_option`, so maybe it can be removed?

I think `sender` can be removed, yes. Half the trigger calls have a sender of `nil`, and the rest either pass the object triggering it separately anyway, or the object can easily be obtained via a global variable or a simple query to $map_factory or something. This means that all registration of events will have one less parameter in their procs, which means any dev with their own event to register will need to edit it anyway to make it compatible. Since they're editing it anyway, they can be expected to also change `Events.onStepTakenFieldMovement += proc ...` to `Events.register(:on_step_taken, :daycare_steps, proc ...)` or whatever it is now, which is why the methods currently in `module Events` can be immediately removed rather than deprecated.

**Comment by Golisopod-User** [comment]
I've renamed `module Events` to `module EventHandlers` just to bring it in line with `MenuHandlers`.  A `module EncounterModifier` definitely existed, however it has been removed by me. I've replaced it with Events instead.

To fix the name translation issue, I've added `_INTL()` to the get_string_option method. I've tested it and it seems to have fixed the issue. I've made the "order" change. I'm not happy with it, since "priority" made more sense to me.

I've also converted all the keys for the debug options and the menu options into symbols. The only strings now used in the Handlers are just the keys of the hash being registered ie "name", "description", "parent", "effect" etc. Should those be changed to symbols too.

**Comment by Golisopod-User** [comment]
Looks like something got messed up in the rebase. I'll need to fix it.

**Comment by Maruno17** [comment]
What makes sense to me is for options higher up in the list to have lower numbers. I was sort of okay with "priority", even though they were ordered in the opposite direction (low -> high) than move priorities, but you said you didn't like that. "order" works. If you can think of an alternative, suggest it.

The keys "name", "description", etc. don't really matter in terms of whether they're a string or symbol. Turning them into symbols will eventually mean all other hashes using strings as keys (such as `MultipleForms`) should also be turned into symbols for consistency. Since the scope of this pull request has ballooned out of all proportion already, it's probably best just to leave the strings for the time being.

**Comment by Golisopod-User** [comment]
I think I'll settle for "order". This PR should be ready to merge.

**Pull request closed without merging**
