### PR TITLE
AI and other Gen 8 Effects

### PR DESCRIPTION
**Pull request by Golisopod-User**
Added Gen 8 effects for
- Rattled
- Rapid Spin
- Leppa Berry
- Ability Patch
- Iron Ball
- Curse
- Teleport
- Quashed battler priority
- Choice Items w.r.t Instruct and Dancer

Added Basic AI for Gen 8 Moves, Items and Abilities. (Move effect scores added as a separate file so that its easy to evaluate. Please merge it with the rest of the scores later)

### CODE REVIEW

**Comment by Maruno17** [comment]
I've skimmed through this commit (except for the move effects AI stuff), and I have some remarks.

- I've read about Iron Ball's effect that changes an incoming move's effectiveness, but it seems weird to me that Iron Ball wouldn't apply this effect if the holder also happened to be affected by Smack Down or whatever. It's still holding Iron Ball. That's why I hadn't made this change myself.

- Will Rattled be triggered by Intimidate if the bearer could have had its Attack lowered by Intimidate but some effect prevented it? Adrenaline Orb triggers that way, and I wonder if both have the same triggers.

- Why have you made Leppa Berry's effect works the way you wrote it? Your code prefers the move with the fewest remaining PP, but from what I've read, it should prefer a move with 0 PP, and failing that, just go with the first move in the moveset with any amount of PP depleted.

- The message you left next to my comment about Iron Head turning into/from a Behemoth move doesn't actually answer my comment. Iron Head's total PP is 15, while the Behemoth moves' total PP is 5. If you start with Iron Head at 15, it would turn into a Behemoth move with 5 (15 capped by the Behemoth move's total PP), and let's say you use the move once so it now has 4 PP. How much PP does it have when it turns back into Iron Head? Does it stick with 4, or go to 14 (total PP minus 1 usage), or maybe go to 12 (because Iron Head's total PP is 3x so it does 3x on the current PP as well)? I suspect it stays at 4, but that's just my opinion.

**Comment by Golisopod-User** [comment]
1. I think the Iron Ball effect has something to do with Inverse Battles or some other battle gimmick that relies on type effectiveness. But it also does seem pretty minor and could be left as is 
2. I don't think it makes sense for Rattled to proc that way really, but this could be tested.
3. I must've misunderstood what was written in the notes for Leppa Berry. I'll correct in a later PR.
4. It gets scaled, so in your example of using Behemoth Blade once, the PP of Iron Head will go down to 12. However, I can't confirm whether the PP is 5 or 4 when Iron Head's PP is 14 (not exactly divisible by 3)

**Comment by Maruno17** [comment]
It looks like you copy-pasted the AI from your Gen 8 mod straight into 007_AI_Move_EffectScores_Gen8.rb, without making sure that the function codes match up to the correct effects. As such, the AI makes no sense.

**Comment by Golisopod-User** [comment]
Whoops mb. I'll push a fix to that in a bit.

**Comment by Golisopod-User** [comment]
The function code changes have been made. I apologize for the inconvenience.

**Pull request merged**
