### PR TITLE
Error message improvements

### PR DESCRIPTION
**Pull request by Marin-MK**
- Added script names in error messages by passing them as `eval` arguments (Data\Scripts.rxdata change)
- Replace PC's username in error messages with "..." and replaced / with \\.

### CODE REVIEW

**Comment by Maruno17** [comment]
Does the PC's username really need removing? Sure, accidental self-doxxing is a thing, but how can you say this is an informative message when it's omitting part of the file path? Perhaps at the very least, replace it with `[username]` instead of `...`?

**Comment by Marin-MK** [comment]
[username] is equally invalid as ...

But I'll just replace it with `USERNAME`

**Comment by Maruno17** [comment]
How is it equally as invalid? Firstly, it shows only one folder has been omitted (`...` could be anything), and secondly, it hints at what the folder's name actually is.

**Comment by Marin-MK** [comment]
I've changed it to `USERNAME`, and also trimmed all excess whitespace off all scripts and standardized all file endings.

**Pull request merged**
