### PR TITLE
Add Boolean module to TrueClass and FalseClass

### PR DESCRIPTION
**Pull request by jonisavo**
The file `002_Ruby Utilities.rb` defines a `Boolean` class that is left unused. I propose turning it into a module and including it into `TrueClass` and `FalseClass`. This makes the `to_i` method available for both classes and allows us to use `validate` on boolean arguments like so:

```ruby
def foo(boolean_arg)
  validate boolean_arg => Boolean
  # ...
end
```

This is possible since we'll be able to do `obj.is_a?(Boolean)`.

### CODE REVIEW

**Comment by Maruno17** [comment]
If it's unused, it can be deleted instead.

**Comment by jonisavo** [comment]
I thought it'd be convenient to be able to do `validate boolean_arg => Boolean` instead of `validate boolean_arg => [TrueClass, FalseClass]`. But I wouldn't be against removing the Boolean class entirely.

**Comment by Marin-MK** [comment]
The purpose of the Boolean class is to be included in TrueClass and FalseClass to allow for #is_a?(Boolean), as well as validate obj => Boolean. Whether or not you want to keep that is up to you.

**Comment by Maruno17** [comment]
Boolean class has been removed.

**Pull request closed without merging**
