### PR TITLE
Gen8 Adding all TR/TMs compatibility up to Crown of Tundra

### PR DESCRIPTION
**Pull request by ErwanBeurier**
Adding all TR compatibility from Sword/Shield (the data comes from Bulbapedia).
Next step: add all TMs compatibility from Sword/Shield + move tutors.
Then: add all Pokémons for Substitute, Encore, Sleep Talk (will do later because different treatment).
Then then: update TMs compatibility to include Crown Thundra DLC.

Note: I only changed PBS/tm.txt.
I didn't alter the other script Data/Scripts/013_Overworld/014_PField_DependentEvents.rb ^^"

### CODE REVIEW

**Comment by kyurejl** [comment]
Replace all Hatenna with Hattena, remove all ALCREMIE_63.

**Comment by kyurejl** [comment]
if you can make the tms.txt of the crown tundra, thank you :)

**Comment by ErwanBeurier** [comment]
> 
> 
> if you can make the tms.txt of the crown tundra, thank you :)

I will, but after the new Pokémons/forms are added to pokemon.txt and pokemonforms.txt ;)

**Comment by kyurejl** [comment]
My PR have all of the forms and mons of Crown Tundra :)

**Comment by kyurejl** [comment]
#48

**Comment by ErwanBeurier** [comment]
Ok I will then 👍 
Added to my TODO list:
 - Add all Move Tutors
 - Add all TMs 
 - Handle Substitute/Endure/Sleep Talk
 - Update to Crown Thundra DLC

**Comment by kyurejl** [comment]
all tms? from gen 8? if not from gen 8 do the PR on the master branch :)

**Comment by ErwanBeurier** [comment]
Added all Move Tutors from Gen 8

@kyurejl I mean all TMS and such of Gen 8 ^^ I assume that all previous TMs are already in tm.txt.

**Comment by kyurejl** [comment]
i think not

**Comment by ErwanBeurier** [comment]
My bad.

**Comment by ErwanBeurier** [comment]
I browsed the tm.txt file in Version18.1 ; apparently all Pokémons up to Zeraora have their TMs (even Ultra-Beasts).
The only missing Pokémon from Gen 7 were Meltan/Melmetal but I added their moves in my previous PR #47

**Comment by ErwanBeurier** [comment]
Added all TMs from Gen 8

New TODO list:
 - Handle Substitute, Endure, Sleep Talk, Rest, Snore, Protect, Attract, Facade, Round (Bulbapedia shows those that do not learn these moves, instead of those that do learn them)
 - Update to Crown Thundra DLC
 - Check if Arceus learns everything
 - Check forms

**Comment by ErwanBeurier** [comment]
Added Substitute, Endure, Sleep Talk, Rest, Snore, Protect, Attract, Facade, Round.
They had a different treatment because Bulbapedia lists the Pokémons that DO NOT learn these moves.

TODO list:
 - Update to Crown Tundra DLC
 - Check if Arceus learns everything
 - Check forms

**Comment by ErwanBeurier** [comment]
Added TM compatibility for the new Pokémons and forms from Crown of Tundra DLC. 

TODO list:
 - Check if Arceus learns everything
 - Check forms

**Comment by ErwanBeurier** [comment]
So, Arceus is not in Gen 8. My guess is it should learn every move that Mew learns, that is, all TMs / TRs / Move tutors except Starter-only moves (Grass/Fire/water pledge, and elemental Hyper beams). 
Should I add Arceus anyway?

New TODO list: 
 - Check forms
[ ¿Should Arceus learn every TM even if it is not in Gen 8?]

**Comment by Maruno17** [comment]
1. Arceus is not Mew. It could never learn all TMs. As with all other Pokémon that don't appear in Gen 8, stick with its Gen 7 compatibilities.

2. Cubone has two different forms because there is a difference between them: the evolution method. A Pokémon doesn't need to have a second form defined in pokemonforms.txt if it's identical to its base form.

**Comment by ErwanBeurier** [comment]
1. and 2. Ok!
I have nothing more to commit, I think it's good.

**Comment by ErwanBeurier** [comment]
I think it's over now :)

**Comment by ErwanBeurier** [comment]
Added the following content from the DLC:
 - All new Pokémons in PBS
 - All new Pokémons forms in PBS
 - All new moves (no scripting was needed)
 - All new abilities (PBS + Script)

TODO:
 - Calyrex's form changes (scripting)

**Comment by ErwanBeurier** [comment]
Added Calyrex form change + Slowpoke evolution.

Done adding TM/TR compatibility + Crown of Tundra content.

**Comment by Golisopod-User** [comment]
Hi there. Would you mind reverting your commits related to the code and PBS (except tm.txt). Your PBS entry for As One and your code for the abilties is incorrect and it will lead to an unnesscessary merge conflict.

**Comment by ErwanBeurier** [comment]
Hi. No problem. I was tired of waiting for someone else to add the Crown of Tundra content so I tried to do it myself. I am not sure why the code for the abilities is wrong but I will trust you. Thank you for your additions!

**Comment by Golisopod-User** [comment]
Ah, you see, the code is wrong because you can't use *= operator with damage multiplers (like the ones in Dragon's Maw and Transistor) that's the error.

**Comment by ErwanBeurier** [comment]
That's strange, I copied/edited the code from Strong Jaw, it uses the *= with base damage...
Anyways, I'm happy someone else coded everything ^^
I realised I forgot to implement "As One" too.

**Pull request merged**
