### PR TITLE
Minor bugfiixes

### PR DESCRIPTION
**Pull request by Golisopod-User**
A few bugfixes to wrap up v20 development.
- Fixed moved bounced back by Magic Coat/Bounced moves affecting battlers they normally shouldn't
- Fixed town map compiler not saving any region names
- Fixed typo in map renderer disposal
- Updated String#blank? method
- Removed Vivillion Forms being based on Trainer's secret id, allowing different locations to have different forms.

### CODE REVIEW

**Comment by Maruno17** [comment]
The change to Magic Coat/Magic Bounce isn't quite right. Currently it will fail to bounce if even a single new target is unaffected, but moves like Growl affect multiple targets and can be bounced and should affect as many targets as possible.

Please leave the code for Vivillon's form in. It's there for a reason. If devs want to change it, they can.

**Comment by Golisopod-User** [comment]
I've addressed the issue you mentioned. I don't think the Vivillion code needs to be added back, since its a similar case to Basculin, Flabebe line and Oricorio, where the form is decided by a random value and cannot be customized, so it'd much rather be removed entirely.

**Comment by Maruno17** [comment]
The forms of Basculin/Flabébé/Oriocorio you encounter depend on the map you're in, which is definitely something the user will be modifying anyway (i.e. they'll make maps). Meanwhile, Vivillon's form depends on your real-world location when you start the game, which means you only have access to one form per save file.

Since we can't/don't want to require an online connection to determine the player's real-world location, the next best thing is to still limit Vivillon to one form per save file but make it random. That's what this code does. It's there because Essentials is mimicking the official games as best it can, and having this code makes it more accurate than not having it. Unless you can provide a better alternative, put the code back in.

Bear in mind that, even with this code, you _can_ write VIVILLON_7 in encounters.txt and other places and it'll work just fine. The one issue is that the code will recalculate the form if it's 0, but if the dev wants to micromanage their Vivillon forms that much, they can be expected to deal with that themselves - Essentials should not make itself a worse copy of the official games for their sake.

**Comment by Golisopod-User** [comment]
We could check the region using the System.user_language similar to how the Pokedex checks for the user region. I've added the code back and will probably tackle this later after I've researched this more.

**Pull request merged**
