### PR TITLE
Small Bug Fixes

### PR DESCRIPTION
**Pull request by Golisopod-User**
Fixed Bug with Mega Evolution
Fixed Bug with Arceus Forms
Removed isUnnerved? method and added the checks to canConsumBerrry?
Rebased my branch of the fork (this should be the last time you see all the commits listed)

### CODE REVIEW

**Comment by Maruno17** [comment]
Looks like you've lost a bunch of code here. Stuff relating to Ripen/Throat Spray/Room Service/Eject Pack/Quick Draw, for a start. Leek has become Stick again (I suggest you just copy Stick to Leek rather than replacing it).

**Comment by Golisopod-User** [comment]
Looks like I missed a bunch of code while rebasing the branch. This should be fixed now. You can merge the PR now.

**Comment by Maruno17** [comment]
Looks like you've still missed out the effect of Quick Draw in Custap Berry/Quick Claw's battle handlers. Is this intentional?

**Comment by Golisopod-User** [comment]
Yes. It was kinda unnecessary because the subPri check in the priority calculating method already handled that effect.

**Pull request merged**
