### PR TITLE
Updated Message

### PR DESCRIPTION
**Pull request by Nathan-mv**
Updated Messages saying the Pokémon was stored in a PC box to SWSH/BDSP ones.

### CODE REVIEW

**Comment by Maruno17** [comment]
While I do like to update text to the latest game's standard, this change removes all mention of which box the Pokémon is being sent to, which I'm hesitant to accept. It's nice to have that information, even though the old messages may be a little clunky. I'm not sure what to think.

**Comment by FL-** [comment]
I prefer to have the metion too, at least until gen 9 or gen 10.

**Comment by Nathan-mv** [comment]
Well what do you think of "Pikachu has been sent to Box 3!".

**Comment by Maruno17** [comment]
That's decent enough. `{1} has been sent to Box \"{2}\"!`. I think it's okay if we omit the mention of transferring to a PC, and also whether the current box is full.

**Pull request merged**
