### PR TITLE
Fixed Grav Apple having the incorrect damage boost 

### PR DESCRIPTION
**Pull request by Keyacom**
In the official games, Grav Apple has a damage boost of 1.5x under Gravity, not 2x. This has been fixed.

Source: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Grav_Apple_(move)). However, I took this from the [French version of the article](https://www.pokepedia.fr/Force_G?oldid=2040910), as Bulbapedia has some backend issues right now (opening most pages gives an HTTP 503 response, but BulbaTech is working on removing this issue).
```
La capacité [Force G] voit sa puissance augmentée de 50% sous Gravité, passant à 120.
|
V
The move [Grav Apple] has its power increased by 50% under Gravity, to 120.
```
Updated the comment above the class definition to account for this change.

### CODE REVIEW

**Comment by Keyacom** [comment]
Also changed the class name to accommodate for this change.

**Comment by Keyacom** [comment]
[Bulbapedia article on Grav Apple](https://bulbapedia.bulbagarden.net/wiki/Grav_Apple_(move)?oldid=3510520). Bulbapedia's backend issues have been fixed.

**Comment by Maruno17** [comment]
The function code "LowerTargetDefense1DoublePowerInGravity" is referenced in an AI script. Can you change that as well to the new name "LowerTargetDefense1PowersUpInGravity"?

**Comment by Keyacom** [comment]
Just fixed this (at first, I didn't notice the new name part). Also, is the change in how the multiplier is calculated because the power must be interpreted as an integer, not as a float?

**Comment by Maruno17** [comment]
I suspect it doesn't matter if the base damage is a float, but multiplying it by 3/2 is at least consistent with, say, "HitsAllFoesAndPowersUpInPsychicTerrain". The change of Grav Apple's function code name is also to make it consistent with this function code.

**Pull request merged**
