### PR TITLE
Day Care bugfixes

### PR DESCRIPTION
**Pull request by FL-**
- Fix some pokémon forms didn't inherit father form when breeding with Ditto.
- Fix a debug daycare UI bug (if you have 2 pokémon on daycare and remove the first by debug menu, the second one disappears from UI).
- ~~Fix pokémon with impossible genders when changing species by debug~~.

### CODE REVIEW

**Comment by FL-** [comment]
Doing a rebase

**Comment by FL-** [comment]
Done

**Comment by Maruno17** [comment]
I don't think your changes related to gender are needed, given my recent commit to the dev branch which fixes the same thing but in a better way. And that change doesn't need porting into the master branch, because it only comes about while debugging and isn't important enough to be fixed immediately.

**Comment by FL-** [comment]
I didn't see your commit. Your commit was almost the same time as mine (less than 10 minutes difference).

Anyway, the gender fix was removed.

**Comment by Maruno17** [comment]
I've just make a commit that includes this change but in a slightly better way. This pull request is no longer needed.

**Comment by FL-** [comment]
I guess that you forgot about the other bugfix.

**Pull request closed without merging**
