### PR TITLE
Description Changer and Bug Fixes

### PR DESCRIPTION
**Pull request by Golisopod-User**
Added a way to change the Description of an Item based on certain conditions. This is useful for fusion items which change their description based on whether a Pokemon is fused or no.

Also Fixed N-Solarizer, N-Lunarizer and DNA Splicers from fusing even though the proper conditions weren't met.

### CODE REVIEW

**Comment by Maruno17** [comment]
There's no need to fiddle with the item descriptions like this. Essentials doesn't have the restriction of "you can only have one fused X at once", so it doesn't make sense to treat the item description as though that restriction was in place. For example, you could have a fused and an unfused Necrozma in your party at the same time, so either description of N-Solarizer is going to be inaccurate for one of them, so why bother changing it?

Not to mention that you're overriding items.txt data, and also the Exp All item sets a precedent for having two separate items that look the same but behave differently in some way (applies an effect/has a different description).

**Comment by Golisopod-User** [comment]
This doesn't only apply to Essentials though. Most fangames will allow only 1 Legendary per game, so this could be useful in that case.

Changing the Description based on the state of fusion of the Pokemon is something that the official games do too, so that's why I tried to implement it in the simplest way I could.

And there can be many applications to a description changer, Eg: Changing the description of some kind of questlog, so that it leads the player in the direction of the next quest.

Finally, the EXP All case is different because the 2 items, EXPALL and EXPALLOFF are different in functionality that's why it makes sense to have 2 items entries. It doesn't make sense to add an extra entry for items which only have a very brief description change based on very specific conditions.

**Comment by Maruno17** [comment]
I'm not saying it can't be done. I'm saying this isn't the way it should be done. An item is an item, and its properties as defined in items.txt are its properties. They shouldn't be messed around with by code. If you want a property to be different, you'll need a different item.

**Comment by Golisopod-User** [comment]
It doesn't make sense to add an extra entry for items which only have a very brief description change based on very specific conditions (like the Fusion Items). But ok, as you say.

**Pull request closed without merging**
